<a href="https://colab.research.google.com/github/nurimammasri/Dicoding-Belajar-Pengembangan-Machine-Learning/blob/main/Submission%2001/Additional/Submission%2001%20-%20imdb_indonesian.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:
! pip install --upgrade --force-reinstall --no-deps kaggle
! mkdir /root/.kaggle/
! cp "/content/drive/My Drive/Machine Learning/kaggle.json" /root/.kaggle/
! chmod 600 /root/.kaggle/kaggle.json

     |████████████████████████████████| 61kB 2.2MB/s 
  Created wheel for kaggle: filename=kaggle-1.5.6-cp36-none-any.whl size=72859 sha256=810260c706633a2198171712704440a17e33724f5eeda25ccf82faa00a6a1104
  Stored in directory: /root/.cache/pip/wheels/57/4e/e8/bb28d035162fb8f17f8ca5d42c3230e284c6aa565b42b72674
Successfully built kaggle
  Found existing installation: kaggle 1.5.6
    Uninstalling kaggle-1.5.6:
      Successfully uninstalled kaggle-1.5.6


In [ ]:
!kaggle datasets download -d antoniuscs/imdb-synopsis-indonesian-movies

  0% 0.00/299k [00:00<?, ?B/s]
100% 299k/299k [00:00<00:00, 90.4MB/s]


In [ ]:
import zipfile

zipref = zipfile.ZipFile('imdb-synopsis-indonesian-movies.zip', 'r')
zipref.extractall()
zipref.close()

In [ ]:
import pandas as pd

df = pd.read_csv('imdb_indonesian_movies_2.csv')
df

judul_film  ...     genre
0                Sunan Kalijaga  ...     Drama
1                           Gie  ...     Drama
2     Guru Bangsa Tjokroaminoto  ...     Drama
3                     POL Movie  ...     Drama
4                 Sang pencerah  ...     Drama
...                         ...  ...       ...
1000            Winter in Tokyo  ...  Romantis
1001            Petualang Cinta  ...  Romantis
1002           Last Night (III)  ...  Romantis
1003              Path of Light  ...  Romantis
1004   Kulihat cinta di matanya  ...  Romantis

[1005 rows x 3 columns]

In [ ]:
df = df.drop(columns=['judul_film'])
df

ringkasan_sinopsis     genre
0     Raden Mas Said putra sulung Tumenggung Wilarik...     Drama
1     Soe Hok Gie adalah seorang aktivis yang hidup ...     Drama
2     Guru Bangsa Tjokroaminoto menceritakan tentang...     Drama
3     POL menceritakan kisah hidup yang luar biasa d...     Drama
4     Perjalanan pahlawan Indonesia KH Ahmad Dahlan ...     Drama
...                                                 ...       ...
1000  Winter in Tokyo berpusat pada kehidupan Ishida...  Romantis
1001  Markonah melarikan diri ke Jakarta karena akan...  Romantis
1002  Tempat aking lebih dari 36 jam, Last Night ada...  Romantis
1003  Proyek baru ini adalah tentang seorang lelaki ...  Romantis
1004  Atika (Meriam Bellina) mantan penyanyi tenar, ...  Romantis

[1005 rows x 2 columns]

In [ ]:
df.head()

ringkasan_sinopsis  genre
0  Raden Mas Said putra sulung Tumenggung Wilarik...  Drama
1  Soe Hok Gie adalah seorang aktivis yang hidup ...  Drama
2  Guru Bangsa Tjokroaminoto menceritakan tentang...  Drama
3  POL menceritakan kisah hidup yang luar biasa d...  Drama
4  Perjalanan pahlawan Indonesia KH Ahmad Dahlan ...  Drama

In [ ]:
category = pd.get_dummies(df['genre'])
df = pd.concat([df, category], axis=1)
df = df.drop(columns='genre')
df

ringkasan_sinopsis  Drama  ...  Laga  Romantis
0     Raden Mas Said putra sulung Tumenggung Wilarik...      1  ...     0         0
1     Soe Hok Gie adalah seorang aktivis yang hidup ...      1  ...     0         0
2     Guru Bangsa Tjokroaminoto menceritakan tentang...      1  ...     0         0
3     POL menceritakan kisah hidup yang luar biasa d...      1  ...     0         0
4     Perjalanan pahlawan Indonesia KH Ahmad Dahlan ...      1  ...     0         0
...                                                 ...    ...  ...   ...       ...
1000  Winter in Tokyo berpusat pada kehidupan Ishida...      0  ...     0         1
1001  Markonah melarikan diri ke Jakarta karena akan...      0  ...     0         1
1002  Tempat aking lebih dari 36 jam, Last Night ada...      0  ...     0         1
1003  Proyek baru ini adalah tentang seorang lelaki ...      0  ...     0         1
1004  Atika (Meriam Bellina) mantan penyanyi tenar, ...      0  ...     0         1

[1005 rows x 6 columns]

In [ ]:
import nltk
import re

nltk.download('stopwords')
nltk.download('wordnet')

from nltk.corpus import stopwords
from nltk.stem import LancasterStemmer
from nltk.stem import WordNetLemmatizer


sw = stopwords.words('indonesian')
stemmer = LancasterStemmer()
lemmatizer = WordNetLemmatizer()

replace_puncts = {'`': "'", '′': "'", '“':'"', '”': '"', '‘': "'"}

strip_chars = [',', '.', '"', ':', ')', '(', '-', '|', ';', "'", '[', ']', '>', '=', '+', '\\', '•',  '~', '@', 
 '·', '_', '{', '}', '©', '^', '®', '`',  '<', '→', '°', '€', '™', '›',  '♥', '←', '×', '§', '″', '′', 'Â', '█', '½', 'à', '…', 
 '“', '★', '”', '–', '●', 'â', '►', '−', '¢', '²', '¬', '░', '¶', '↑', '±', '¿', '▾', '═', '¦', '║', '―', '¥', '▓', '—', '‹', '─', 
 '▒', '：', '¼', '⊕', '▼', '▪', '†', '■', '’', '▀', '¨', '▄', '♫', '☆', 'é', '¯', '♦', '¤', '▲', 'è', '¸', '¾', 'Ã', '⋅', '‘', '∞', 
 '∙', '）', '↓', '、', '│', '（', '»', '，', '♪', '╩', '╚', '³', '・', '╦', '╣', '╔', '╗', '▬', '❤', 'ï', 'Ø', '¹', '≤', '‡', '√', ]

puncts = ['!', '?', '$', '&', '/', '%', '#', '*','£']


def clean_text(x):
    x = str(x)
    x = x.lower()
    x = re.sub(r"(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9]\.[^\s]{2,})", "url", x)
    for k, v in replace_puncts.items():
        x = x.replace(k, f' {v} ')
        
    for punct in strip_chars:
        x = x.replace(punct, ' ') 
    
    for punct in puncts:
        x = x.replace(punct, f' {punct} ')
        
    x = x.replace(" '", " ")
    x = x.replace("' ", " ")
    x = x.strip()
    return x

def stopwords1(text):
    '''a function for removing the stopword'''
    # removing the stop words and lowercasing the selected words
    text = [word.lower() for word in text.split() if word.lower() not in sw]
    # joining the list of words with space separator
    return " ".join(text)

def stemming(text):    
    '''a function which stems each word in the given text'''
    text = [stemmer.stem(word) for word in text.split()]
    return " ".join(text) 

def lemm(text):    
    text = [lemmatizer.lemmatize(word) for word in text.split()]
    return " ".join(text)

def clean_length(text):
    text = [word for word in text.split() if len(word) > 2]
    return " ".join(text)

def text_processing(X):
    X=X.apply(stopwords1)
    X=X.apply(clean_text)
    # X=X.apply(stemming)
    # X=X.apply(lemm)
    X=X.apply(clean_length)
    return X

print(sw)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
['ada', 'adalah', 'adanya', 'adapun', 'agak', 'agaknya', 'agar', 'akan', 'akankah', 'akhir', 'akhiri', 'akhirnya', 'aku', 'akulah', 'amat', 'amatlah', 'anda', 'andalah', 'antar', 'antara', 'antaranya', 'apa', 'apaan', 'apabila', 'apakah', 'apalagi', 'apatah', 'artinya', 'asal', 'asalkan', 'atas', 'atau', 'ataukah', 'ataupun', 'awal', 'awalnya', 'bagai', 'bagaikan', 'bagaimana', 'bagaimanakah', 'bagaimanapun', 'bagi', 'bagian', 'bahkan', 'bahwa', 'bahwasanya', 'baik', 'bakal', 'bakalan', 'balik', 'banyak', 'bapak', 'baru', 'bawah', 'beberapa', 'begini', 'beginian', 'beginikah', 'beginilah', 'begitu', 'begitukah', 'begitulah', 'begitupun', 'bekerja', 'belakang', 'belakangan', 'belum', 'belumlah', 'benar', 'benarkah', 'benarlah', 'berada', 'berakhir', 'berakh

In [ ]:
sinopsis = text_processing(df['ringkasan_sinopsis'])
label = df[['Drama', 'Horor', 'Komedi', 'Laga', 'Romantis']].values

In [ ]:
sinopsis_clean = sinopsis.values
sinopsis_clean

array(['raden mas said putra sulung tumenggung wilarikta kerajaan majapahit berkuasa wilayah tuban sekeluarga miskin menderita busung lapar prihatin hati nuraninya tergugah menolong mencoba diam diam mengambil makanan lumbung orang tuanya perbuatan disetujui orang tuanya dihukum sekap gudang makanan itu kejadian said tumbuh dewasa betah tinggal rumah berkelana daerah daerah lainnya sanalah betapa penyelewengan kesewenang wenangan lurah munafik mengkambing hitamkan tumenggung menutupi kejahatannya laporan said ayahnya sadar dianggap sumber fitnah kelananya bertemu sunan bonang mencurahkan ilmunya said tapa pinggir kali berkat ketabahannya menghadapi cobaan said nur kekuatan ilahi diangkat wali terkenal deretan nama sembilan wali wali sanga nama sunan kalijaga',
       'soe hok gie aktivis hidup enam puluhan terletak era gelap sejarah modern indonesia gie interpretasi berdasarkan jurnalnya',
       'guru bangsa tjokroaminoto menceritakan lepas era tanam paksa 1800 hindia belanda memasuki

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(sinopsis_clean, label, test_size=0.2)

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer(num_words=1000, oov_token='<OOV>')
tokenizer.fit_on_texts(x_train)

sequence_train = tokenizer.texts_to_sequences(x_train)
sequence_test = tokenizer.texts_to_sequences(x_test)

padded_train = pad_sequences(sequence_train, padding='post', maxlen=100, truncating='post')
padded_test = pad_sequences(sequence_test, padding='post', maxlen=100, truncating='post')

In [ ]:
print(padded_train)
print(padded_test)

[[ 27   1 542 ...   0   0   0]
 [ 18   1   1 ...   0   0   0]
 [226   1 314 ...   1   1   0]
 ...
 [448 825   1 ...   0   0   0]
 [  1 218  46 ...   0   0   0]
 [226   1 150 ...   0   0   0]]
[[  1   1   1 ...   0   0   0]
 [  1   1   1 ...   0   0   0]
 [351   1   1 ... 346  41   1]
 ...
 [906 218   1 ...   1 178   1]
 [  5  43   1 ...   0   0   0]
 [ 57 221   1 ...   0   0   0]]


In [ ]:
print(len(padded_train[0]))
print(len(padded_test[0]))

100
100


In [ ]:
import tensorflow as tf

model = tf.keras.Sequential([
                             tf.keras.layers.Embedding(1000, 128, input_length=100),
                             tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64, return_sequences=True,recurrent_dropout=0.5)),
                             tf.keras.layers.Dropout(0.6),
                             tf.keras.layers.GlobalMaxPool1D(),
                             tf.keras.layers.Dense(48, activation='relu'),
                             tf.keras.layers.Dropout(0.2),
                             tf.keras.layers.Dense(5, activation='softmax')
])

model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

model.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_9 (Embedding)      (None, 100, 128)          128000    
_________________________________________________________________
bidirectional_15 (Bidirectio (None, 100, 128)          98816     
_________________________________________________________________
dropout_10 (Dropout)         (None, 100, 128)          0         
_________________________________________________________________
global_max_pooling1d_1 (Glob (None, 128)               0         
_________________________________________________________________
dense_19 (Dense)             (None, 48)                6192      
_________________________________________________________________
dropout_11 (Dropout)         (None, 48)                0         
_________________________________________________________________
dense_20 (Dense)             (None, 5)                

In [ ]:
num_epochs = 30
history = model.fit(
    padded_train,
    y_train,
    epochs=num_epochs,
    validation_data=(padded_test, y_test)
)

Epoch 1/30
26/26 [==============================] - 30s 1s/step - loss: 1.6125 - accuracy: 0.2015 - val_loss: 1.6056 - val_accuracy: 0.2836
Epoch 2/30
26/26 [==============================] - 30s 1s/step - loss: 1.5938 - accuracy: 0.2674 - val_loss: 1.6021 - val_accuracy: 0.2537
Epoch 3/30
26/26 [==============================] - 29s 1s/step - loss: 1.5626 - accuracy: 0.3022 - val_loss: 1.5837 - val_accuracy: 0.3532
Epoch 4/30
26/26 [==============================] - 29s 1s/step - loss: 1.4652 - accuracy: 0.4751 - val_loss: 1.5269 - val_accuracy: 0.4577
Epoch 5/30
26/26 [==============================] - 30s 1s/step - loss: 1.2408 - accuracy: 0.5522 - val_loss: 1.4358 - val_accuracy: 0.4229
Epoch 6/30
26/26 [==============================] - 30s 1s/step - loss: 0.9386 - accuracy: 0.6604 - val_loss: 1.3934 - val_accuracy: 0.4179
Epoch 7/30
26/26 [==============================] - 30s 1s/step - loss: 0.7341 - accuracy: 0.7475 - val_loss: 1.3922 - val_accuracy: 0.4577
Epoch 8/30
26/26 [==